@BuddyErp.Api_HostAddress = http://localhost:5080

GET {{BuddyErp.Api_HostAddress}}/api/health
Accept: application/json

###

POST {{BuddyErp.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "loginId": "president",
  "password": "test1234!"
}

###
