// <auto-generated />
using System;
using BuddyErp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuddyErp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728055408_AddMemberDueNotes")]
    partial class AddMemberDueNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.Announcement", b =>
                {
                    b.Property<long>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("announcement_id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("author_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("AnnouncementId");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.Expense", b =>
                {
                    b.Property<long>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("expense_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12)
                        .HasColumnType("decimal(12,0)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpenseItem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("expense_item");

                    b.Property<bool>("IsSettled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_settled");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payer_name");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_date");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ExpenseId");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.InventoryItem", b =>
                {
                    b.Property<long>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_item_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("item_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("ItemName")
                        .IsUnique();

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.InventoryPurchase", b =>
                {
                    b.Property<long>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12)
                        .HasColumnType("decimal(12,0)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPurchased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_purchased");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("item_name");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("purchased_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("PurchaseId");

                    b.ToTable("inventory_purchases", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MatchAttendance", b =>
                {
                    b.Property<long>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("attendance_id");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("AttendanceId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ScheduleId", "MemberId")
                        .IsUnique();

                    b.ToTable("match_attendances", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MatchParticipant", b =>
                {
                    b.Property<long>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("participant_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GuestName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("guest_name");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_guest");

                    b.Property<long?>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.HasKey("ParticipantId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ScheduleId", "GuestName")
                        .IsUnique();

                    b.HasIndex("ScheduleId", "MemberId")
                        .IsUnique();

                    b.ToTable("match_participants", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MatchSchedule", b =>
                {
                    b.Property<long>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsMatchFeePaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_match_fee_paid");

                    b.Property<decimal>("MatchFee")
                        .HasPrecision(12)
                        .HasColumnType("decimal(12,0)")
                        .HasColumnName("match_fee");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("OpponentContact")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("opponent_contact");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("opponent_name");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payer_name");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("venue_name");

                    b.HasKey("ScheduleId");

                    b.ToTable("match_schedules", (string)null);

                    b.HasData(
                        new
                        {
                            ScheduleId = 1L,
                            CreatedAt = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            IsMatchFeePaid = false,
                            MatchFee = 0m,
                            Notes = "",
                            OpponentName = "신풍 FC",
                            PayerName = "윤승범",
                            StartsAt = new DateTime(2026, 8, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VenueName = "신트리 공원"
                        });
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.Member", b =>
                {
                    b.Property<long>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<int>("BirthYear")
                        .HasColumnType("int")
                        .HasColumnName("birth_year");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasUniform")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("has_uniform");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("member_name");

                    b.Property<string>("MemberStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("member_status");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PrimaryPosition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("primary_position");

                    b.Property<string>("SecondaryPosition")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("secondary_position");

                    b.Property<int?>("UniformNumber")
                        .HasColumnType("int")
                        .HasColumnName("uniform_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("MemberId");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MemberDue", b =>
                {
                    b.Property<long>("MemberDueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("member_due_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12)
                        .HasColumnType("decimal(12,0)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DueMonth")
                        .HasColumnType("int")
                        .HasColumnName("due_month");

                    b.Property<int>("DueYear")
                        .HasColumnType("int")
                        .HasColumnName("due_year");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("MemberDueId");

                    b.HasIndex("MemberId", "DueYear", "DueMonth")
                        .IsUnique();

                    b.ToTable("member_dues", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MemberDueNote", b =>
                {
                    b.Property<long>("MemberDueNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("member_due_note_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DueYear")
                        .HasColumnType("int")
                        .HasColumnName("due_year");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("MemberDueNoteId");

                    b.HasIndex("MemberId", "DueYear")
                        .IsUnique();

                    b.ToTable("member_due_notes", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.QuarterFormation", b =>
                {
                    b.Property<long>("QuarterFormationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("quarter_formation_id");

                    b.Property<string>("FormationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("formation_code");

                    b.Property<int>("QuarterNumber")
                        .HasColumnType("int")
                        .HasColumnName("quarter_number");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("QuarterFormationId");

                    b.HasIndex("ScheduleId", "QuarterNumber")
                        .IsUnique();

                    b.ToTable("quarter_formations", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.QuarterLineupPlayer", b =>
                {
                    b.Property<long>("LineupPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("lineup_player_id");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint")
                        .HasColumnName("participant_id");

                    b.Property<int>("PositionOrder")
                        .HasColumnType("int")
                        .HasColumnName("position_order");

                    b.Property<long>("QuarterFormationId")
                        .HasColumnType("bigint")
                        .HasColumnName("quarter_formation_id");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("slot_code");

                    b.HasKey("LineupPlayerId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("QuarterFormationId", "ParticipantId")
                        .IsUnique();

                    b.HasIndex("QuarterFormationId", "SlotCode")
                        .IsUnique();

                    b.ToTable("quarter_lineup_players", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login_id");

                    b.Property<long?>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.Expense", b =>
                {
                    b.HasOne("BuddyErp.Api.Data.Entities.MatchSchedule", "Schedule")
                        .WithOne("Expense")
                        .HasForeignKey("BuddyErp.Api.Data.Entities.Expense", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MatchAttendance", b =>
                {
                    b.HasOne("BuddyErp.Api.Data.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuddyErp.Api.Data.Entities.MatchSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MatchParticipant", b =>
                {
                    b.HasOne("BuddyErp.Api.Data.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuddyErp.Api.Data.Entities.MatchSchedule", "Schedule")
                        .WithMany("Participants")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MemberDue", b =>
                {
                    b.HasOne("BuddyErp.Api.Data.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MemberDueNote", b =>
                {
                    b.HasOne("BuddyErp.Api.Data.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.QuarterFormation", b =>
                {
                    b.HasOne("BuddyErp.Api.Data.Entities.MatchSchedule", "Schedule")
                        .WithMany("QuarterFormations")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.QuarterLineupPlayer", b =>
                {
                    b.HasOne("BuddyErp.Api.Data.Entities.MatchParticipant", "Participant")
                        .WithMany("LineupPlayers")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuddyErp.Api.Data.Entities.QuarterFormation", "QuarterFormation")
                        .WithMany("LineupPlayers")
                        .HasForeignKey("QuarterFormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("QuarterFormation");
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.User", b =>
                {
                    b.HasOne("BuddyErp.Api.Data.Entities.Member", "Member")
                        .WithOne()
                        .HasForeignKey("BuddyErp.Api.Data.Entities.User", "MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MatchParticipant", b =>
                {
                    b.Navigation("LineupPlayers");
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.MatchSchedule", b =>
                {
                    b.Navigation("Expense");

                    b.Navigation("Participants");

                    b.Navigation("QuarterFormations");
                });

            modelBuilder.Entity("BuddyErp.Api.Data.Entities.QuarterFormation", b =>
                {
                    b.Navigation("LineupPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
